import argparse
from datetime import datetime
from html import escape
from pathlib import Path

from scanner.target import check_target
from scanner.headers import check_security_headers


VERSION = "1.0.0"
REPORTS = Path("reports")


def main():
    parser = argparse.ArgumentParser(
        description="VulnForge - Automated Web Security Scanner"
    )
    parser.add_argument("--url", required=True)
    args = parser.parse_args()

    url = args.url.strip()

    if not url.startswith(("http://", "https://")):
        url = "http://" + url

    REPORTS.mkdir(exist_ok=True)

    now = datetime.now()
    stamp = now.strftime("%Y%m%d_%H%M%S")
    date = now.strftime("%Y-%m-%d %H:%M:%S")

    txt = REPORTS / f"scan_{stamp}.txt"
    html = REPORTS / f"scan_{stamp}.html"

    print("=" * 55)
    print("VULNFORGE")
    print("Automated Web Security Scanner")
    print(f"Version {VERSION}")
    print("=" * 55)
    print(f"[*] Target: {url}")
    print("[*] Checking target...")

    target = check_target(url)
    findings = []

    if target["success"]:
        print(f"[+] HTTP {target['status_code']}")
        print("[*] Checking security headers...")
        findings = check_security_headers(target["headers"])
        print(f"[+] Findings: {len(findings)}")
    else:
        print("[!] Target could not be reached.")
        print(f"[!] {target['error']}")

    counts = {
        "CRITICAL": 0,
        "HIGH": 0,
        "MEDIUM": 0,
        "LOW": 0,
        "INFO": 0
    }

    for item in findings:
        level = item["severity"].upper()
        if level in counts:
            counts[level] += 1

    text = [
        "VULNFORGE SECURITY REPORT",
        "=" * 55,
        f"Target: {url}",
        f"Scan date: {date}",
        "",
        "SUMMARY",
        "-" * 55,
        f"Critical: {counts['CRITICAL']}",
        f"High:     {counts['HIGH']}",
        f"Medium:   {counts['MEDIUM']}",
        f"Low:      {counts['LOW']}",
        f"Info:     {counts['INFO']}",
        f"Total:    {len(findings)}",
        "",
        "FINDINGS",
        "-" * 55
    ]

    for number, item in enumerate(findings, 1):
        text += [
            "",
            f"[{number}] {item['type']}",
            f"Severity: {item['severity']}",
            f"Header: {item['parameter']}",
            f"Description: {item['description']}",
            f"Recommendation: {item['recommendation']}"
        ]

    text += [
        "",
        "=" * 55,
        "Generated by VulnForge",
        "For authorized security testing only."
    ]

    txt.write_text("\n".join(text), encoding="utf-8")

    rows = ""

    for item in findings:
        rows += (
            "<tr>"
            f"<td>{escape(item['type'])}</td>"
            f"<td>{escape(item['severity'])}</td>"
            f"<td>{escape(item['parameter'])}</td>"
            f"<td>{escape(item['description'])}</td>"
            f"<td>{escape(item['recommendation'])}</td>"
            "</tr>"
        )

    if not rows:
        rows = "<tr><td colspan='5'>No findings detected.</td></tr>"

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VulnForge Report</title>
<style>
body {{
font-family: Arial,sans-serif;
margin:30px;
background:#f4f4f4;
}}
main {{
max-width:1100px;
margin:auto;
background:white;
padding:25px;
}}
table {{
width:100%;
border-collapse:collapse;
}}
th,td {{
border:1px solid #ccc;
padding:10px;
text-align:left;
}}
th {{
background:#eee;
}}
</style>
</head>
<body>
<main>
<h1>VulnForge Security Report</h1>
<p><b>Target:</b> {escape(url)}</p>
<p><b>Scan date:</b> {escape(date)}</p>

<h2>Summary</h2>
<ul>
<li>Critical: {counts['CRITICAL']}</li>
<li>High: {counts['HIGH']}</li>
<li>Medium: {counts['MEDIUM']}</li>
<li>Low: {counts['LOW']}</li>
<li>Info: {counts['INFO']}</li>
<li>Total: {len(findings)}</li>
</ul>

<h2>Findings</h2>
<table>
<tr>
<th>Type</th>
<th>Severity</th>
<th>Header</th>
<th>Description</th>
<th>Recommendation</th>
</tr>
{rows}
</table>

<p>Generated by VulnForge.</p>
<p>For authorized security testing only.</p>
</main>
</body>
</html>"""

    html.write_text(page, encoding="utf-8")

    print("[+] TXT report:", txt)
    print("[+] HTML report:", html)
    print("[+] Scan completed.")


if __name__ == "__main__":
    main()
